<?php

function shift_cypher_menu() {
    $items['shift_cypher'] = array(
        'title' => 'Shift Cypher Encryption',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('shift_cypher_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );

    $items['encryption_success'] = array(
        'title' => 'Encryption',
        'page callback' => 'encryption',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );

    return $items;
}

function shift_cypher_form() {
    $form['shift_direction'] = array(
        '#title' => 'Shift direction',
        '#type' => 'textfield',
        '#description' => t('Please enter a shift direction (right/left)'),
        '#element_validate' => array('element_validate_left_right'),
        '#required' => TRUE,
    );

    $form['shift_value'] = array(
        '#title' => 'Shift value',
        '#type' => 'textfield',
        '#description' => t('Value to shift by'),
        '#element_validate' => array('element_validate_integer_positive'),
        '#required' => TRUE,
    );

    $form['phrase'] = array(
        '#title' => 'phrase',
        '#type' => 'textfield',
        '#description' => 'Enter a phrase to encrypt (no special characters except spaces and punctuation)',
        '#element_validate' => array('element_validate_punctuation'),
        '#required' => TRUE,
    );

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Encrypt',
    );

    return $form;
}

function element_validate_left_right($element) {
    if ((strtolower($element['#value']) != 'left') && (strtolower($element['#value']) != 'right')) {
        form_error($element, t('Shift direction must be left or right'));
    }
}

function element_validate_punctuation($element) {
    if (!preg_match('/^[a-zA-Z,.!? ]*$/', $element['#value'])){
        form_error($element, t('The phrase can only contain letters, spaces, and punctuation.'));
    }
}

function shift_cypher_form_submit($form, &$form_state) {
    $direction = strtolower($form_state['values']['shift_direction']);
    $shift_value = $form_state['values']['shift_value'];
    $phrase = strtolower($form_state['values']['phrase']);
    $phrase_array = str_split($phrase);
    $encrypted_array = array();

    foreach ($phrase_array as $letter) {
        $ascii_letter = ord($letter);
        if($ascii_letter >= 97 && $ascii_letter <= 122) {
            if($direction == 'left') {
                if($ascii_letter - $shift_value >= 97) {
                    $encrypted_letter = chr($ascii_letter - $shift_value);
                } else {
                    $encrypted_letter = chr($ascii_letter + 26 - $shift_value);
                }
            } elseif($direction == 'right') {
                if($ascii_letter + $shift_value <= 122) {
                    $encrypted_letter = chr($ascii_letter + $shift_value);
                } else {
                    $encrypted_letter = chr($ascii_letter - 26 + $shift_value);
                }
            }
        } else {
            $encrypted_letter = $letter;
        }

        array_push($encrypted_array, $encrypted_letter);
    }

    $_SESSION['encryption'] = implode($encrypted_array);
    $form_state['redirect'] = 'encryption_success';
}

function encryption() {
    $output = $_SESSION['encryption'];
    return '<h3>' . $output . '</h3>';
}
